# Generated by Django 4.2.7 on 2025-09-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy_setting',
            field=models.CharField(choices=[('public', 'Public - Anyone can view my profile'), ('private', 'Private - Only I can view my profile'), ('registered', 'Registered Users - Only logged-in users can view my profile')], default='public', help_text='Control who can view your profile', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default-avatar.png', upload_to='profile_pics/'),
        ),
    ]
