# Generated by Django 4.2.7 on 2025-09-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Your Facebook profile URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_username',
            field=models.CharField(blank=True, help_text='Your Instagram username (without @)', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Your LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='snapchat_username',
            field=models.CharField(blank=True, help_text='Your Snapchat username', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='tiktok_username',
            field=models.CharField(blank=True, help_text='Your TikTok username (without @)', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, help_text='Your GitHub username', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Your Twitter/X username (without @)', max_length=50),
        ),
    ]
