# Generated by Django 4.2.7 on 2025-10-17 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profile_facebook_url_profile_instagram_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, help_text='Upload an audio file (MP3, WAV, OGG)', null=True, upload_to='post_audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'], message='Please upload a valid audio file (MP3, WAV, or OGG)')]),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4, WebM, OGG)', null=True, upload_to='post_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'], message='Please upload a valid video file (MP4, WebM, or OGG)')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a featured image for the post', null=True, upload_to='blog_images/'),
        ),
    ]
