# Generated by Django 4.2.7 on 2025-10-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_audio_post_video_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False, help_text='Designates whether this post should be featured on the homepage.'),
        ),
    ]
